from django.core.management.base import BaseCommand
from jewellery_products.models import Category, Product, Testimonial


class Command(BaseCommand):
    help = 'Seed database with Trinora Jewels data using media folder images'

    def handle(self, *args, **options):
        # Clear existing data
        self.stdout.write('Clearing existing data...')
        Product.objects.all().delete()
        Category.objects.all().delete()
        Testimonial.objects.all().delete()

        # ─── Categories ───────────────────────────────────────────────────
        self.stdout.write('Creating categories...')
        categories_data = [
            {
                'name': 'Earrings',
                'slug': 'earrings',
                'description': 'Minimal, trendy, and statement anti-tarnish earrings for everyday glam. Waterproof and skin-friendly.',
                'image': 'Earrings/Earrings 01.jpeg',
            },
            {
                'name': 'Chains',
                'slug': 'chains',
                'description': 'Elegant anti-tarnish chains and necklaces that elevate your look instantly. Waterproof and long-lasting.',
                'image': 'Chains/Chain 01.jpeg',
            },
            {
                'name': 'Bracelets',
                'slug': 'bracelets',
                'description': 'Perfect anti-tarnish bracelets and bangles for a stylish and modern touch. Sweat-proof design.',
                'image': 'Bracelet/Bracelet 01.jpeg',
            },
            {
                'name': 'Mangalsutra',
                'slug': 'mangalsutra',
                'description': 'Modern and traditional anti-tarnish mangalsutra designs for everyday wear. Lightweight and hypoallergenic.',
                'image': 'Mangalsutra/Mangalsutra 01.jpeg',
            },
            {
                'name': 'Rings',
                'slug': 'rings',
                'description': 'Trendy anti-tarnish rings with premium finish. Waterproof and skin-friendly for everyday wear.',
                'image': 'Rings/Ring 01.jpeg',
            },
            {
                'name': 'Watch',
                'slug': 'watch',
                'description': 'Stylish waterproof fashion watches with premium anti-tarnish finish. Perfect for modern women.',
                'image': 'Watch/Watch 01.jpeg',
            },
        ]

        categories = {}
        for cat_data in categories_data:
            cat = Category.objects.create(**cat_data)
            categories[cat.name] = cat
            self.stdout.write(f'  OK Category: {cat.name}')

        # ─── Products ─────────────────────────────────────────────────────
        self.stdout.write('Creating products...')
        products_data = [
            # EARRINGS
            {'category': 'Earrings', 'image': 'Earrings/Earrings 01.jpeg', 'name': 'Classic Gold Stud Earrings', 'description': 'Elegant gold stud earrings designed with anti-tarnish coating for long-lasting shine. These hypoallergenic studs are perfect for sensitive skin and everyday wear. Waterproof and sweat-proof design ensures they stay shiny all day long.', 'price': 599, 'sale_price': 449, 'material': 'Premium Alloy, Gold Finish', 'is_featured': True},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 02.jpeg', 'name': 'Floral Drop Earrings', 'description': 'Beautiful floral drop earrings with anti-tarnish premium finish. These lightweight earrings are ideal for college wear and casual outings. Hypoallergenic material ensures comfort for all-day wear.', 'price': 699, 'sale_price': 499, 'material': 'Premium Alloy, Gold Finish', 'is_featured': True},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 03.jpeg', 'name': 'Crystal Hoop Earrings', 'description': 'Stunning crystal hoop earrings with waterproof anti-tarnish coating. These trendy hoops stay shiny even in water and sweat. Perfect for working professionals who want to look stylish all day.', 'price': 799, 'sale_price': None, 'material': 'Premium Alloy, Crystal', 'is_featured': True},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 04.jpeg', 'name': 'Pearl Stud Earrings', 'description': 'Delicate pearl stud earrings with anti-tarnish gold finish. These skin-friendly earrings are perfect for office wear and special occasions. The pearl design adds a touch of elegance to any outfit.', 'price': 649, 'sale_price': 499, 'material': 'Premium Alloy, Faux Pearl', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 05.jpeg', 'name': 'Rose Gold Jhumka', 'description': 'Traditional jhumka earrings in trendy rose gold anti-tarnish finish. These sweat-proof earrings are perfect for festive occasions and daily wear. Lightweight design ensures all-day comfort.', 'price': 899, 'sale_price': 699, 'material': 'Premium Alloy, Rose Gold Finish', 'is_featured': True},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 06.jpeg', 'name': 'Statement Chandbali Earrings', 'description': 'Bold chandbali earrings with premium anti-tarnish coating. These waterproof statement earrings are perfect for parties and celebrations. Hypoallergenic design is safe for all skin types.', 'price': 999, 'sale_price': 749, 'material': 'Premium Alloy, Gold Finish', 'is_featured': True},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 07.jpeg', 'name': 'Minimal Bar Earrings', 'description': 'Simple and elegant bar earrings with waterproof anti-tarnish finish. These minimalist earrings are perfect for everyday styling. Skin-friendly material suitable for sensitive skin.', 'price': 499, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 08.jpeg', 'name': 'Butterfly Stud Earrings', 'description': 'Cute butterfly stud earrings with anti-tarnish premium coating. These hypoallergenic studs are perfect for college girls and young women. Waterproof design keeps them shiny all day.', 'price': 549, 'sale_price': 399, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 09.jpeg', 'name': 'Tassel Drop Earrings', 'description': 'Trendy tassel drop earrings with anti-tarnish finish. These lightweight earrings add drama to any outfit. Sweat-proof design ensures they look great from morning to night.', 'price': 749, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 10.jpeg', 'name': 'Geometric Hoop Earrings', 'description': 'Modern geometric hoop earrings with anti-tarnish waterproof coating. Perfect for working women who love contemporary jewellery. Hypoallergenic material is safe for sensitive skin.', 'price': 699, 'sale_price': 549, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 11.jpeg', 'name': 'Kundan Stud Earrings', 'description': 'Traditional kundan stud earrings with modern anti-tarnish finish. These waterproof earrings blend tradition with contemporary style. Perfect for festive occasions and ethnic wear.', 'price': 849, 'sale_price': 649, 'material': 'Premium Alloy, Kundan Work', 'is_featured': True},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 12.jpeg', 'name': 'Star Charm Earrings', 'description': 'Playful star charm earrings with anti-tarnish gold coating. These cute earrings are perfect for college girls and casual outings. Hypoallergenic and skin-friendly for all-day wear.', 'price': 549, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 13.jpeg', 'name': 'Oval Link Earrings', 'description': 'Stylish oval link earrings with waterproof anti-tarnish finish. These minimal earrings are perfect for everyday styling at office or college. Long-lasting shine guaranteed.', 'price': 649, 'sale_price': 499, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 14.jpeg', 'name': 'Floral Jhumka Earrings', 'description': 'Beautiful floral jhumka earrings with premium anti-tarnish coating. These sweat-proof earrings are perfect for everyday ethnic wear. Lightweight design ensures comfortable all-day wear.', 'price': 899, 'sale_price': 699, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 15.jpeg', 'name': 'Leaf Drop Earrings', 'description': 'Elegant leaf drop earrings with anti-tarnish waterproof finish. These nature-inspired earrings add grace to any outfit. Hypoallergenic material keeps skin comfortable all day.', 'price': 749, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 16.jpeg', 'name': 'Diamond Cut Hoop Earrings', 'description': 'Sparkling diamond-cut hoop earrings with anti-tarnish premium coating. These waterproof hoops catch the light beautifully. Perfect for parties and special occasions.', 'price': 799, 'sale_price': 649, 'material': 'Premium Alloy, Gold Finish', 'is_featured': True},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 17.jpeg', 'name': 'Moon & Star Earrings', 'description': 'Celestial moon and star earrings with anti-tarnish finish. These trendy earrings are perfect for college girls. Waterproof and sweat-proof for all-day wear.', 'price': 599, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 18.jpeg', 'name': 'Thread Tassel Earrings', 'description': 'Boho-style thread tassel earrings with anti-tarnish gold accents. These lightweight earrings add colour and movement to your look. Perfect for casual and festive occasions.', 'price': 649, 'sale_price': 499, 'material': 'Premium Alloy, Thread', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 19.jpeg', 'name': 'Coin Drop Earrings', 'description': 'Boho coin drop earrings with waterproof anti-tarnish finish. These trendy earrings are perfect for casual and festive wear. Hypoallergenic design for sensitive skin.', 'price': 699, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 20.jpeg', 'name': 'Twisted Gold Hoops', 'description': 'Elegant twisted gold hoops with anti-tarnish premium coating. These waterproof hoops are perfect for everyday wear and special occasions. Long-lasting shine with minimal maintenance.', 'price': 749, 'sale_price': 599, 'material': 'Premium Alloy, Gold Finish', 'is_featured': True},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 21.jpeg', 'name': 'Peacock Jhumka Earrings', 'description': 'Stunning peacock design jhumka earrings with anti-tarnish finish. These hypoallergenic earrings are perfect for ethnic occasions and weddings. Waterproof design keeps them shiny longer.', 'price': 999, 'sale_price': 799, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 22.jpeg', 'name': 'Square Stud Earrings', 'description': 'Modern square stud earrings with anti-tarnish premium coating. These minimal studs are perfect for office and casual wear. Skin-friendly material for comfortable all-day use.', 'price': 549, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 23.jpeg', 'name': 'Floral Chandelier Earrings', 'description': 'Glamorous floral chandelier earrings with anti-tarnish waterproof finish. These statement earrings are perfect for parties and celebrations. Premium quality with long-lasting shine.', 'price': 1099, 'sale_price': 849, 'material': 'Premium Alloy, Gold Finish', 'is_featured': True},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 24.jpeg', 'name': 'Heart Stud Earrings', 'description': 'Sweet heart stud earrings with anti-tarnish gold finish. These cute earrings are perfect for everyday wear and gifting. Hypoallergenic and waterproof for all-day comfort.', 'price': 499, 'sale_price': 399, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earring 25.jpeg', 'name': 'Shell Drop Earrings', 'description': 'Boho shell drop earrings with anti-tarnish premium accents. These trendy earrings add a coastal vibe to your style. Waterproof and sweat-proof for beach and outdoor wear.', 'price': 699, 'sale_price': None, 'material': 'Shell, Premium Alloy', 'is_featured': False},
            {'category': 'Earrings', 'image': 'Earrings/Earrings 26.jpeg', 'name': 'Long Chain Earrings', 'description': 'Dramatic long chain earrings with waterproof anti-tarnish finish. These statement earrings are perfect for evening occasions and parties. Premium quality with long-lasting shine.', 'price': 849, 'sale_price': 649, 'material': 'Premium Alloy, Gold Finish', 'is_featured': True},
            # CHAINS
            {'category': 'Chains', 'image': 'Chains/Chain 16.jpeg', 'name': 'The Fortuna Horseshoe Amulet Snake Chain', 'description': 'A sleek, sculptural horseshoe pendant symbolizing protection and luck, suspended on a premium liquid-gold snake chain. Features a mirror-like glow that catches every light. Smooth snake chain designed not to pull on fine hair or irritate the neck. Solid construction for daily, 24/7 wear. Anti-tarnish waterproof coating ensures long-lasting shine.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': True},
            {'category': 'Chains', 'image': 'Chains/Chain 01.jpeg', 'name': 'The Prism Heart Drop Lariat', 'description': 'A vibrant vertical drop necklace featuring seven multi-colored heart crystals. Designed for those who love dopamine dressing. The Y-silhouette elongates the neckline and is perfect for layering. Each colored crystal is safely enclosed in a gold frame. High-quality Zirconia stones that maintain their sparkle even after water exposure.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Crystal', 'is_featured': True},
            {'category': 'Chains', 'image': 'Chains/Chain 02.jpeg', 'name': 'The Solstice Radiance Heart Pendant', 'description': 'A vintage-inspired heart featuring a textured sunburst pattern with a brilliant crystal core. Deep-etched rays reflect light in a starburst effect. Satellite chain features delicate gold beads for a trendy, textured look. Premium clear crystal center adds an elegant touch. Anti-tarnish and waterproof for lasting shine.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Crystal', 'is_featured': False},
            {'category': 'Chains', 'image': 'Chains/Chain 03.jpeg', 'name': 'The Eternity Layered Heart Necklace', 'description': 'A modern, double-frame heart design with a shimmering crystal halo. A top-seller for romantic gifting. Features trending elongated paperclip chain links for a 2026 aesthetic. Hand-set micro-pave crystals offer a high-end fine jewelry shimmer. Lightweight design provides a substantial look without the heavy weight on the neck.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Crystal', 'is_featured': True},
            {'category': 'Chains', 'image': 'Chains/Chain 04.jpeg', 'name': 'The Scripted Love 3D Puffy Heart', 'description': 'A classic, high-shine 3D puffy heart engraved with "Love" in an elegant script font. Bold, rounded heart that stands out against any outfit. Precision engraving is deep-etched to remain visible for years. The perfect staple piece that matches any outfit from casual to formal. Waterproof anti-tarnish finish for daily wear.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Chains', 'image': 'Chains/Chain 05.jpeg', 'name': 'The Lumina Heart Satellite Necklace', 'description': 'A minimalist dream featuring a smooth, high-shine puffy heart pendant on a unique satellite beaded chain. Subtle gold beads add a modern twist to the classic heart necklace. Mirror-finish heart is highly reflective for a premium real-gold look. Lightweight and perfectly balanced for stacking with other chains.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Chains', 'image': 'Chains/Chain 06.jpeg', 'name': 'The Opulence Shell Heart Pendant', 'description': 'A sophisticated heart pendant featuring a genuine Mother-of-Pearl style inlay, framed by a thick gold border on a twisted rope chain. Iridescent inlay catches the light with a soft, pearly shimmer. Rope chain provides a sturdy, luxurious vintage feel. Raised gold edge gives extra protection for the inlay. Anti-tarnish waterproof design.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Pearl Inlay', 'is_featured': True},
            {'category': 'Chains', 'image': 'Chains/Chain 07.jpeg', 'name': 'The Stellar Princess Cut Necklace', 'description': 'A dainty, ultra-minimalist piece featuring a single princess-cut (square) AAA-grade Zirconia on a shimmering petal-link chain. Princess cut brilliance offers a modern, sharp sparkle. Petal chain links are flattened to reflect light like tiny mirrors. The perfect barely-there piece for professional or daily wear.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Zirconia', 'is_featured': False},
            {'category': 'Chains', 'image': 'Chains/Chain 08.jpeg', 'name': 'The Midnight Emerald-Cut Noir Pendant', 'description': 'A bold, gender-neutral geometric pendant featuring a deep black rectangular inlay set in a sleek gold frame. Clean geometric lines appeal to fans of modern, architectural jewelry. Suspended on a high-durability box chain that resists snapping. The deep black center makes the gold frame pop brilliantly. Waterproof anti-tarnish finish.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Black Inlay', 'is_featured': False},
            {'category': 'Chains', 'image': 'Chains/Chain 09.jpeg', 'name': 'The Eclipse Sculptural Oval Necklace', 'description': 'A designer-inspired piece featuring an oval black stone encased in a molten or organic-shaped gold frame. The irregular gold border gives it a custom, handmade boutique look. Features a premium, silky-smooth snake chain that sits flat against the skin. Large enough to be a focal point while remaining chic and simple.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Black Stone', 'is_featured': False},
            {'category': 'Chains', 'image': 'Chains/Chain 10.jpeg', 'name': 'The Aria Twisted Heart Satellite Necklace', 'description': 'An elegant open heart pendant with a beautiful rope-texture finish, paired with a delicate gold beaded satellite chain. Twisted rope detail adds a sophisticated, high-end texture to a classic symbol. Beaded satellite chain provides extra shimmer and a modern aesthetic. The open-heart design feels effortless and lightweight on the neck.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Chains', 'image': 'Chains/Chain 11.jpeg', 'name': 'The Heritage Heart Floral Mangalsutra', 'description': 'A stunning fusion piece featuring a heart-shaped pendant with an inner floral crystal motif, set on a traditional black-beaded gold chain. Perfectly blends sacred tradition with modern jewelry design. Hand-set micro-pave Zirconia crystals in the floral center for maximum brilliance. Traditional black beads are securely integrated into the gold-plated chain.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Crystal, Black Beads', 'is_featured': True},
            {'category': 'Chains', 'image': 'Chains/Chain 12.jpeg', 'name': 'The Guardian Evil Eye Heart Layering Set', 'description': 'A powerful symbol of protection featuring a vibrant blue Evil Eye set inside a crystal-encrusted heart, paired with a trendy flat herringbone chain. Combines a sleek flat snake chain with a dainty pendant chain for a pre-layered effect. High-quality enamel Nazar eye surrounded by a sparkling halo. Bold gold herringbone chain provides a liquid-metal shine.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Enamel, Crystal', 'is_featured': False},
            {'category': 'Chains', 'image': 'Chains/Chain 13.jpeg', 'name': 'The Serendipity Crystal Heart Lariat', 'description': 'A delicate Y-shaped lariat featuring a series of shimmering crystal-set hearts that drop elegantly down the chest. Vertical silhouette designed to elongate the neck — pairs perfectly with V-neck tops. Four individual crystal hearts catch the light from every angle. Adjustable drop gives a jewelry-forward design that feels custom-made.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Crystal', 'is_featured': False},
            {'category': 'Chains', 'image': 'Chains/Chain 14.jpeg', 'name': 'The Unity Eternal Knot Heart', 'description': 'A minimalist masterpiece featuring a polished gold heart that transitions into a knot design, representing unbreakable bonds. Sculptural, seamless, fluid look that follows the Quiet Luxury trend. Suspended on a premium, smooth-gliding silky snake chain for ultimate comfort. Expertly buffed to a high-shine finish that rivals solid gold.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Chains', 'image': 'Chains/Chain 15.jpeg', 'name': 'The Coquette Ribbon Bow Necklace', 'description': 'A charming and feminine golden bow pendant suspended on a delicate beaded satellite chain. Perfect for the Coquette and romantic fashion aesthetic. Subtle gold beads on the satellite chain add a touch of texture and extra sparkle. Elegant enough for a formal event, yet playful enough for daily wear.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Chains', 'image': 'Chains/Chain 17.jpeg', 'name': 'The Manifest 11:11 Angel Number Necklace', 'description': 'A sleek rectangular bar pendant engraved with the powerful angel number 11:11. Designed for those who believe in magic and synchronicity. A daily reminder to stay positive and manifest your dreams. Clean, modern geometric design that looks stunning when layered. Deep-etched precision engraving ensures the numbers never fade.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Chains', 'image': 'Chains/Chain 18.jpeg', 'name': 'The Secret Garden Rose Inlay Necklace', 'description': 'A boutique-style oval medallion with an organic molten gold edge, featuring a beautiful golden rose embossed on a white pearlescent inlay. The irregular gold frame gives it a custom, handmade feel. Combines classic floral motifs with a modern, textured gold finish. Paired with a fine ball chain for a delicate, feminine look.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Pearl Inlay', 'is_featured': False},
            {'category': 'Chains', 'image': 'Chains/Chain 19.jpeg', 'name': 'The Lucky Charm Zirconia Clover', 'description': 'A stunning four-leaf clover pendant where each leaf is a heart-shaped, high-grade Zirconia crystal. Set on a silky snake chain. AAA-grade crystals catch the light from every angle for maximum brilliance. Combines the Good Luck clover symbol with the symbol of love (hearts). Sturdy, polished gold loop keeps the pendant securely in place.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Zirconia', 'is_featured': True},
            # BRACELETS
            {'category': 'Bracelets', 'image': 'Bracelet/Bracelet 01.jpeg', 'name': 'The Olympus Diamond Greek Key Bangle', 'description': 'A bold, architectural cuff featuring the iconic Greek fret pattern, fully encrusted with shimmering micro-crystals for a high-jewelry look. Represents infinity and unity through the traditional Greek pattern. Every line of the pattern is accented with precision-cut stones. Mirror-polished inside for a silk-smooth finish and maximum comfort. Anti-tarnish waterproof coating.', 'price': 349, 'sale_price': None, 'material': 'Premium Alloy, Crystal', 'is_featured': True},
            {'category': 'Bracelets', 'image': 'Bracelet/Bracelet 02.jpeg', 'name': 'The Helix Diamond Link Bracelet', 'description': 'A sophisticated bangle that mimics the look of a luxury watch strap with alternating polished gold and crystal-studded links. Provides the structured look of a bangle with the visual texture of a link bracelet. Boutique finish that is perfect for stacking with a gold watch. Anti-tarnish waterproof design for lasting shine and daily comfort.', 'price': 349, 'sale_price': None, 'material': 'Premium Alloy, Crystal', 'is_featured': True},
            {'category': 'Bracelets', 'image': 'Bracelet/Bracelet 03.jpeg', 'name': 'The Pure High-Shine Gold Kada', 'description': 'A classic, ultra-slim gold band with a flat mirror-finish surface. The ultimate Quiet Luxury staple. Lightweight design for maximum comfort during long workdays. The perfect base piece for any jewelry stack. Anti-tarnish and waterproof for worry-free daily wear. Hypoallergenic and skin-friendly for sensitive skin.', 'price': 349, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Bracelets', 'image': 'Bracelet/Bracelet 04.jpeg', 'name': 'The Trinity Layered Statement Bangle', 'description': 'A pre-stacked masterpiece featuring three distinct textures: a beaded edge, a sparkling crystal center, and a bold curb chain motif. Get the look of three bracelets with the convenience of one. Contrasting textures capture light from every angle for a dramatic effect. Anti-tarnish waterproof coating ensures long-lasting beauty.', 'price': 349, 'sale_price': None, 'material': 'Premium Alloy, Crystal', 'is_featured': True},
            {'category': 'Bracelets', 'image': 'Bracelet/Bracelet 05.jpeg', 'name': 'The Prosperity Clover Cuff', 'description': 'A wide, open-worked cuff featuring four gold bands meeting at a central sunburst clover motif outlined in shimmering crystals. Designer-inspired look that represents luck and fortune. Breathable multi-band structure feels light on the wrist. Anti-tarnish waterproof finish for lasting shine. Perfect for festive occasions and everyday wear.', 'price': 349, 'sale_price': None, 'material': 'Premium Alloy, Crystal', 'is_featured': False},
            {'category': 'Bracelets', 'image': 'Bracelet/Bracelet 06.jpeg', 'name': 'The Vanguard Evil Eye Cable Bangle', 'description': 'A modern take on protection jewelry featuring multiple Evil Eye charms and crystal spacers on a flexible gold-toned cable wire. Magnetic or screw clasp stays securely on the wrist even during active movement. Multiple charms ensure the protection symbol is always visible. Waterproof anti-tarnish design for daily wear.', 'price': 349, 'sale_price': None, 'material': 'Premium Alloy, Enamel, Crystal', 'is_featured': False},
            {'category': 'Bracelets', 'image': 'Bracelet/Bracelet 07.jpeg', 'name': 'The Parallel Crystal Groove Bangle', 'description': 'A structured gold bangle featuring parallel recessed grooves with a central line of brilliant-cut crystals. Geometric precision with clean, sharp lines for a professional look. Box clasp features a high-quality side-opening mechanism. Waterproof anti-tarnish coating ensures long-lasting shine. Perfect for office and formal occasions.', 'price': 349, 'sale_price': None, 'material': 'Premium Alloy, Crystal', 'is_featured': False},
            {'category': 'Bracelets', 'image': 'Bracelet/Bracelet 08.jpeg', 'name': 'The Olympus Greek Key Bangle', 'description': 'A bold, architectural cuff featuring the iconic Greek fret pattern in a sleek, all-metal polished finish. Represents infinity and unity through the timeless Greek design. Secure hinge clasp allows easy snap-on and off with a seamless side lock. Premium high-gloss gold finish that is anti-tarnish and waterproof for everyday confidence.', 'price': 349, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Bracelets', 'image': 'Bracelet/Bracelet 09.jpeg', 'name': 'The Noir Royale Triple Band Bangle', 'description': 'A high-fashion wide cuff featuring triple gold bands accented with three square-cut black onyx-style stones and a crystal-encrusted border. High contrast — deep black stones against the gold and white crystals create a luxurious Royal look. Best worn alone as a focal point for evening wear. Anti-tarnish waterproof design.', 'price': 349, 'sale_price': None, 'material': 'Premium Alloy, Black Stone, Crystal', 'is_featured': True},
            {'category': 'Bracelets', 'image': 'Bracelet/Bracelet 10.jpeg', 'name': 'The Matrix Dual-Texture Bangle', 'description': 'A unique split-design bangle featuring a textured grid pattern on one half and a continuous line of crystals on the other. Dual aesthetic — can be rotated to show either the bold texture or the elegant sparkle. Durable hinge designed for longevity and frequent wear. Anti-tarnish waterproof finish for lasting beauty.', 'price': 349, 'sale_price': None, 'material': 'Premium Alloy, Crystal', 'is_featured': False},
            {'category': 'Bracelets', 'image': 'Bracelet/Bracelet 11.jpeg', 'name': 'The Midnight Empress Triple Band Bangle', 'description': 'A stunning wide-frame cuff featuring five parallel gold bands accented with three square-cut black onyx-style stones and brilliant crystal borders. Top and bottom bands are fully encrusted with AAA-grade Zirconia. High-contrast luxury look with deep black stones against gold. Sturdy side-opening hinge mechanism for easy wear.', 'price': 349, 'sale_price': None, 'material': 'Premium Alloy, Black Stone, Zirconia', 'is_featured': False},
            {'category': 'Bracelets', 'image': 'Bracelet/Bracelet 12.jpeg', 'name': 'The Vendome Crystal Nail Bangle', 'description': 'A designer-inspired masterpiece that transforms a simple nail into a luxury accessory — sleek minimal style. A worldwide trending design that represents strength and fashion. Features hand-set crystals on the nail head and tip for a premium touch. Anatomically designed to sit perfectly on the wrist. Anti-tarnish waterproof coating.', 'price': 349, 'sale_price': None, 'material': 'Premium Alloy, Crystal', 'is_featured': False},
            {'category': 'Bracelets', 'image': 'Bracelet/Bracelet 13.jpeg', 'name': 'The Vendome Crystal Nail Bangle Glam', 'description': 'A designer-inspired masterpiece that transforms a simple nail into a luxury accessory — fully encrusted glam version. A worldwide trending style that represents strength and fashion at its finest. Fully covered in hand-set crystals for an all-over sparkle effect. Flexible fit anatomically designed to sit perfectly on the wrist.', 'price': 349, 'sale_price': None, 'material': 'Premium Alloy, Crystal', 'is_featured': True},
            # MANGALSUTRA
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 01.jpeg', 'name': 'The Radiant Bloom Mangalsutra', 'description': 'A delicate and sophisticated piece featuring a floral-inspired central pendant. The interlocking golden arcs encase a cluster of shimmering stones, creating a look that is both timeless and trendy. Sleek single-chain design with classic black beads. High-grade cubic zirconia for a diamond-like finish. Perfect for daily office wear or casual outings.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Cubic Zirconia, Black Beads', 'is_featured': True},
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 02.jpeg', 'name': 'The Majestic Wing Mangalsutra', 'description': 'Make a statement with this nature-inspired design. The pendant features two graceful, stone-studded leafy wings that meet at a brilliant solitaire drop, symbolizing growth and togetherness. Intricate leaf detailing with micro-pave stone setting. Elegant solitaire-style hanging stone. Lightweight yet impactful design for special occasions.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Crystal, Black Beads', 'is_featured': True},
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 03.jpeg', 'name': 'The Royal Crest Mangalsutra', 'description': 'Designed for the woman who loves intricate artistry. This piece features a symmetrical, vintage-inspired crest pattern adorned with marquise-cut stones for maximum sparkle. Ornate geometric pendant design. Premium marquise and round-cut stone combination. Adjustable chain length for a personalized fit.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Marquise Crystal, Black Beads', 'is_featured': False},
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 04.jpeg', 'name': 'The Golden Lattice Mangalsutra', 'description': 'A contemporary take on the traditional mangalsutra. The square pendant features a unique textured lattice pattern on one side and a star-cluster of stones on the other, offering a modern 3D look. Unique textured gold-tone finish. Compact, sturdy pendant ideal for active lifestyles. Minimalist bead placement for a barely-there feel.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Crystal, Black Beads', 'is_featured': False},
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 05.jpeg', 'name': 'The Celestial Crescent Mangalsutra', 'description': 'Capture the beauty of the night sky with this crescent moon design. The pendant is heavily embellished with clear crystals, featuring a delicate heart-shaped stone nestled in the curve. Trendy crescent moon and heart motif. High-shine polish with maximum light reflection. Pairs beautifully with both Indian and Western outfits.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Crystal, Black Beads', 'is_featured': False},
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 06.jpeg', 'name': 'The Solitaire Square Mangalsutra', 'description': 'A bold yet minimalist choice. Features a large, princess-cut central stone held in a textured golden frame, hanging from a classic beaded chain. Statement princess-cut cubic zirconia. Unique textured basket setting. Clean, geometric look for the modern professional. Anti-tarnish and waterproof for daily office wear.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Cubic Zirconia, Black Beads', 'is_featured': True},
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 07.jpeg', 'name': 'The Floral Harmony Mangalsutra', 'description': 'Elegance in full bloom. This horizontal pendant features a delicate row of five-petaled flowers, finished with a dainty pear-shaped drop for added movement. Intricate floral micro-pave work. Graceful pear-cut dangling stone. Ideal for festive wear or bridal gifting. Lightweight and hypoallergenic for all-day comfort.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Crystal, Black Beads', 'is_featured': False},
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 08.jpeg', 'name': 'The Infinite Love Mangalsutra', 'description': 'Symbolize your bond with this romantic design. A shimmering heart-shaped outline is linked with a sleek infinity-style twist, creating a beautiful layered effect. Heart and infinity symbolic motif. Seamlessly integrated pendant design. Lightweight and comfortable for 24/7 wear. Waterproof anti-tarnish coating.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Crystal, Black Beads', 'is_featured': False},
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 09.jpeg', 'name': 'The Triple Blossom Mangalsutra', 'description': 'A playful and feminine piece featuring three delicate stone flowers cascading vertically. A fresh, vertical take on traditional floral patterns. Vertical triple-flower drop pendant. Marquise-cut stones for a petal-like appearance. Perfect for deep-neck outfits. Anti-tarnish waterproof design for lasting beauty.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Marquise Crystal, Black Beads', 'is_featured': False},
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 10.jpeg', 'name': 'The Royal Teardrop Mangalsutra', 'description': 'Pure luxury in a compact form. This pendant features a majestic crown-like top that flows into a halo-set teardrop stone, radiating classic royal vibes. Premium teardrop halo setting. Gold-beaded chain detailing for a traditional touch. High-grade stones with exceptional brilliance. Waterproof anti-tarnish finish.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Halo Crystal, Black Beads', 'is_featured': True},
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 11.jpeg', 'name': 'The Ruby Rose Mangalsutra', 'description': 'A touch of color for the traditional soul. Features a sparkling quatrefoil floral pendant with a vibrant ruby-pink teardrop bead hanging gracefully at the center. Eye-catching ruby-colored accent stone. Classic floral motif with high-grade cubic zirconia. Delicate gold-beaded chain for an ethnic appeal. Hypoallergenic and skin-friendly.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, CZ, Ruby Accent, Black Beads', 'is_featured': False},
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 12.jpeg', 'name': 'The Grand Blossom Mangalsutra', 'description': 'A lavish, sprawling floral design that sits beautifully on the collarbone. Multiple smaller blossoms lead to a large, brilliant central flower for a truly festive look. Multi-flower garland style pendant. High-intensity sparkle with mixed-cut stones. Bold design perfect for weddings and celebrations.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Mixed Crystal, Black Beads', 'is_featured': True},
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 13.jpeg', 'name': 'The Entwined Infinity Mangalsutra', 'description': 'Modernity meets romance. Features two interlocking stone-studded ovals, accented by a tiny floral cluster on the side, representing two lives beautifully joined. Unique interlocking oval infinity pendant. Asymmetrical floral detailing. Sleek and contemporary; pairs well with office wear. Waterproof anti-tarnish coating.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Crystal, Black Beads', 'is_featured': False},
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 14.jpeg', 'name': 'The Petal Arch Mangalsutra', 'description': 'A wide, arched pendant that follows the natural curve of your neckline. Each petal is a shimmering marquise stone, meeting at a central round-cut brilliant. Wide arch silhouette for a fuller look. Premium marquise-cut stone setting. Elegant and lightweight despite its grand appearance. Anti-tarnish waterproof design.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Marquise Crystal, Black Beads', 'is_featured': False},
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 15.jpeg', 'name': 'The Onyx Teardrop Mangalsutra', 'description': 'For the woman who loves bold contrasts. This premium piece features a royal halo setting surrounding a deep, mystical black onyx-style stone. Unique black central teardrop stone. Luxurious double-beaded chain design. High-fashion look that stands out in any crowd. Waterproof anti-tarnish coating for lasting beauty.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Black Stone, Black Beads', 'is_featured': False},
            {'category': 'Mangalsutra', 'image': 'Mangalsutra/Mangalsutra 16.jpeg', 'name': 'The Triple Halo Mangalsutra', 'description': 'Triple the brilliance! Features three distinct circular and teardrop halos linked together, each housing a shimmering dancing stone at its core. Unique three-halo cluster design. Full beaded traditional chain for a rich, festive feel. Exceptional light refraction that truly shines at evening events. Anti-tarnish waterproof finish.', 'price': 299, 'sale_price': None, 'material': 'Premium Alloy, Halo Crystal, Black Beads', 'is_featured': True},
            # RINGS
            {'category': 'Rings', 'image': 'Rings/Ring 01.jpeg', 'name': 'Gold-Tone Pave Wave Band', 'description': 'A wide, structured band with a distinctive S-curve or wave flowing through the center. One side of the wave is smooth gold while the other is encrusted with a line of pave-set cubic zirconia. Asymmetrical design creates a dynamic look that stands out compared to traditional flat bands. Anti-tarnish PVD gold coating for long-lasting shine. Polished interior for all-day comfort.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Cubic Zirconia', 'is_featured': True},
            {'category': 'Rings', 'image': 'Rings/Ring 02.jpeg', 'name': 'Geometric Bar-Link Pave Ring', 'description': 'A structured, flat-top band divided into rectangular sections or bars. Each alternating section is inset with a cluster of micro-pave crystals, creating a rhythmic, architectural look. Segmented design with vertical gold bars providing bold contrast to the sparkling stones. High-polish mirror-like finish on the sides. Clean geometric lines for a unisex appeal.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Micro-Pave Crystal', 'is_featured': True},
            {'category': 'Rings', 'image': 'Rings/Ring 03.jpeg', 'name': 'Tapered Pave Cathedral Ring', 'description': 'A dome-style band that is wider at the top and tapers toward the bottom. The center features a curved row of graduated crystals that follow the arc of the ring, framed by smooth, rounded gold edges. Graduated setting with stones larger in the center and smaller toward the sides. Ergonomic tapered shape for better finger movement and comfort.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Graduated Crystal', 'is_featured': False},
            {'category': 'Rings', 'image': 'Rings/Ring 04.jpeg', 'name': 'Double-Row Inset Crystal Band', 'description': 'A thick, high-polish gold band featuring two parallel rows of brilliant crystals. The stones are flush-set (embedded into the metal), creating a smooth surface that will not snag on clothing. Sleek, low-profile flush setting highly practical for daily use. Substantial feel that is premium and heavy on the finger. Anti-tarnish waterproof coating.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Flush-Set Crystal', 'is_featured': False},
            {'category': 'Rings', 'image': 'Rings/Ring 05.jpeg', 'name': 'Laurel Leaf Eternity Band', 'description': 'A continuous band featuring a repeating carved leaf or wheat pattern. Each leaf motif is centered with a single sparkling crystal, symbolizing growth and eternal life. Textured finish with intricate carvings for a vintage, hand-crafted look. Full eternity pattern and stones go all the way around the finger. Stackable with simple bands or statement rings.', 'price': 249, 'sale_price': None, 'material': 'Premium Alloy, Crystal', 'is_featured': True},
            # WATCH
            {'category': 'Watch', 'image': 'Watch/Watch 01.jpeg', 'name': 'Elegant Crystal Dial Gold Watch', 'description': 'Upgrade your everyday style with this elegant crystal dial gold watch. Designed with a sparkling crystal bezel and a beautiful patterned bracelet, this watch adds a luxurious touch to your look. Premium gold-plated finish with crystal-studded dial design. Stylish bracelet pattern strap that is lightweight and comfortable. Perfect for casual and festive wear. PAN India delivery available.', 'price': 499, 'sale_price': None, 'material': 'Premium Alloy, Crystal Bezel', 'is_featured': True},
            {'category': 'Watch', 'image': 'Watch/Watch 02.jpeg', 'name': 'Classic Minimal Gold Wrist Watch', 'description': 'A timeless classic watch designed for modern women. Features a sleek round dial with a stylish metal strap, giving a sophisticated and elegant appearance. Elegant round dial design with premium gold finish metal strap. Lightweight and durable with a stylish minimal look. Ideal for office wear and daily fashion styling. PAN India delivery available.', 'price': 499, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': True},
            {'category': 'Watch', 'image': 'Watch/Watch 03.jpeg', 'name': 'Luxury Link Bracelet Watch', 'description': 'This luxury bracelet-style watch combines jewelry and functionality in one beautiful design. The decorative link chain strap and crystal dial make it a perfect statement piece. Jewelry-style bracelet strap with crystal embellished dial. Elegant gold finish with comfortable fit for daily wear. The perfect gift for women who love stylish accessories.', 'price': 599, 'sale_price': None, 'material': 'Premium Alloy, Crystal', 'is_featured': False},
            {'category': 'Watch', 'image': 'Watch/Watch 04.jpeg', 'name': 'Premium Fashion Gold Watch', 'description': 'Add a touch of sophistication to your outfit with this premium fashion gold watch. The sleek round dial and elegant metal strap create a luxurious appearance suitable for both casual and formal occasions. Classic round dial with high-quality gold plating. Stylish and durable strap that is an elegant everyday accessory. Perfect for gifting.', 'price': 499, 'sale_price': None, 'material': 'Premium Alloy, Gold Finish', 'is_featured': False},
            {'category': 'Watch', 'image': 'Watch/Watch 05.jpeg', 'name': 'Trinora Pearl Chain Bracelet Watch', 'description': 'Add elegance and charm to your everyday style with this beautiful pearl chain bracelet watch. Designed with a delicate multi-layer chain and pearl detailing, this watch perfectly combines jewelry and functionality. Elegant bracelet-style with multi-layer gold chain design. Beautiful pearl detailing with a lightweight, comfortable fit. Stylish round dial with clear numbers. Perfect for casual and festive outfits.', 'price': 899, 'sale_price': None, 'material': 'Premium Alloy, Pearl, Gold Chain', 'is_featured': True},
            {'category': 'Watch', 'image': 'Watch/Watch 06.jpeg', 'name': 'Pink Floral Petal Charm Watch', 'description': 'A highly feminine watch featuring a small round dial with a crystal-encrusted bezel. Instead of a traditional strap, it uses a thin gold-tone chain accented with pink enamel floral charms. Enamel detailing with soft pink enamel finish that mimics flower petals. Doubles as a delicate bracelet — ideal for ethnic wear or summer dresses. Adjustable fit with lobster claw clasp and extender chain.', 'price': 599, 'sale_price': None, 'material': 'Premium Alloy, Enamel Charms, Crystal', 'is_featured': False},
            {'category': 'Watch', 'image': 'Watch/Watch 07.jpeg', 'name': 'Gold-Tone Crystal Bezel Bangle Watch', 'description': 'A classic, sophisticated timepiece with a round white dial and a stunning crystal bezel. The strap is a semi-rigid bangle style with a distinctive split-path or cut-out design near the watch face. Pave crystal bezel encrusted with fine crystals for a high-shine luxury look. Ergonomic bangle design keeps the watch face centered on the wrist. Clean dial with easy-to-read markers balancing the ornate strap.', 'price': 599, 'sale_price': None, 'material': 'Premium Alloy, Pave Crystal, Bangle Strap', 'is_featured': False},
        ]

        for p_data in products_data:
            cat_name = p_data.pop('category')
            Product.objects.create(
                category=categories[cat_name],
                **p_data
            )

        self.stdout.write(self.style.SUCCESS(f'  Created {Product.objects.count()} products'))

        # ─── Testimonials ─────────────────────────────────────────────────
        self.stdout.write('Creating testimonials...')
        testimonials_data = [
            {
                'name': 'Sneha Patil',
                'location': 'Pune, Maharashtra',
                'text': 'I have been wearing the anti-tarnish earrings from Trinora for 3 months now and they still look brand new! Even after wearing in rain and gym. Absolutely love the quality. Will definitely buy more.',
                'rating': 5, 'is_active': True,
            },
            {
                'name': 'Priya Sharma',
                'location': 'Mumbai, Maharashtra',
                'text': 'Ordered the layered chain necklace and the crystal bracelet. Both are absolutely stunning and have not tarnished at all even after daily wear. The packaging was beautiful too. Trinora is my go-to jewellery brand now!',
                'rating': 5, 'is_active': True,
            },
            {
                'name': 'Ananya Reddy',
                'location': 'Hyderabad, Telangana',
                'text': 'The mangalsutra I ordered is so elegant and lightweight. Perfect for office wear. The anti-tarnish quality is amazing — wears it daily and it still shines like new. Fast delivery and great packaging!',
                'rating': 5, 'is_active': True,
            },
            {
                'name': 'Kavya Nair',
                'location': 'Bengaluru, Karnataka',
                'text': 'Trinora jewellery is the best! I have sensitive skin but these pieces never cause any irritation. The waterproof quality is real — I wore my bracelet while swimming and it still shines. Amazing quality at this price!',
                'rating': 5, 'is_active': True,
            },
            {
                'name': 'Ritu Singh',
                'location': 'Delhi, NCR',
                'text': 'Bought the rose gold jhumkas and the crystal mangalsutra as a gift for my sister. She was absolutely delighted! The quality is premium and the designs are trendy yet traditional. Will recommend Trinora to everyone!',
                'rating': 5, 'is_active': True,
            },
        ]

        for t_data in testimonials_data:
            Testimonial.objects.create(**t_data)

        self.stdout.write(self.style.SUCCESS(
            f'\nDatabase seeded successfully!\n'
            f'   Categories   : {Category.objects.count()}\n'
            f'   Products     : {Product.objects.count()}\n'
            f'   Testimonials : {Testimonial.objects.count()}\n'
        ))
